### PR TITLE
Propagating GattcRead errors into callback

### LINKED ISSUE #113: GattcRead errors ignored, not propagated into callback
Errors reading GATT attributes are ignored (promise rejecting). 
Errors should be provided in the callback for the operation.

https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/a9de121d0f18eaad3b153f2d06694783f2d51757/api/adapter.js#L1399
https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/a9de121d0f18eaad3b153f2d06694783f2d51757/api/adapter.js#L1417

Example of error that is ignored:
app.html:1 Uncaught (in promise) Error: Error occured when adding vendor specific 128-bit UUID. Errorcode: NRF_ERROR_NO_MEM (0x4)

Promise.reject (async)
_converter.uuidToDriver @ /home/kere/tools/nrfconnect-2.2.1/resources/app.asar/node_modules/pc-ble-driver-js/api/adapter.js:1383
_adapter.addVendorspecificUUID @ /home/kere/tools/nrfconnect-2.2.1/resources/app.asar/node_modules/pc-ble-driver-js/api/util/sdConv.…:144

### PR DESCRIPTION
**Pull request by mathiasap**
Should now pass error to callback. Fixes #113

https://github.com/NordicSemiconductor/pc-ble-driver-js/issues/113

### CODE REVIEW

File: test/common.js [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+    7: '7',
+    8: '8',
+    9: '9',
+    10: 'a',
+    11: 'b',
+    12: 'c',
+    13: 'd',
+    14: 'e',
+    15: 'f',
+    16: 'f',
```
Comment (bencefr) [inline test/common.js]: I think (16) was not intentional. I suggest a simpler solution: `const dec2hexStr = '0123456789abcedf'.split('')`.

File: api/adapter.js [hunk 2]
```diff
@@ -1459,22 +1467,35 @@ class Adapter extends EventEmitter {
...
+                    addVsUuidToDriver(attribute.uuid)
+                    .then(() => emitCharacteristicAdded(attribute))
+                    .catch(err => {
+                        delete this._gattOperationsMap[device.instanceId];
+                        this.emit('error', _makeError('addVsUuidToDriver error', err));
+                        gattOperation.callback('Failed to add characteristic uuid to driver');
+                    });
+                } else if (handle === attribute.valueHandle) {
+                    attribute.value = data;
+                    emitCharacteristicAdded(attribute);
```
Comment (bencefr) [inline api/adapter.js]: Looks like GH lost my earlier comment about this one. Anyhow, this new function returns a promise which can reject and is not handled here. This can lead to further issues. I suggest to consider simpler non-promise based solution.

Comment (mathiasap) [reply api/adapter.js]: Good point. There was no reason for it to return a promise in the first place.
